#! /usr/bin/env python

import sys
import os

sys.stdout.write("\x1b[5i")
if len(sys.argv) > 1:
    for filename in sys.argv[1:]:
        if not os.path.isfile(filename):
            sys.exit(filename + " is not a file")
        with open(filename, 'r') as fp:
            sys.stdout.write(fp.read())
else:
    sys.stdout.write(sys.stdin.read())
sys.stdout.write("\x1b[4i")
